# Generated by Django 5.2.12 on 2026-03-19 14:34

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("SUNDAY_SERVICE", "Sunday Service"),
                            ("MIDWEEK_SERVICE", "Midweek Service"),
                            ("PRAYER_MEETING", "Prayer Meeting"),
                            ("YOUTH_MEETING", "Youth Meeting"),
                            ("CHOIR_REHEARSAL", "Choir Rehearsal"),
                            ("SPECIAL_EVENT", "Special Event"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=40,
                    ),
                ),
                ("service_date", models.DateField(db_index=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-service_date", "start_time", "title", "id"),
            },
        ),
        migrations.CreateModel(
            name="MemberAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("LATE", "Late"),
                            ("EXCUSED", "Excused"),
                        ],
                        default="PRESENT",
                        max_length=20,
                    ),
                ),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="member_attendances",
                        to="members.member",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_attendances",
                        to="attendance.serviceevent",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="AttendanceSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("men_count", models.PositiveIntegerField(default=0)),
                ("women_count", models.PositiveIntegerField(default=0)),
                ("children_count", models.PositiveIntegerField(default=0)),
                ("visitor_count", models.PositiveIntegerField(default=0)),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_summary",
                        to="attendance.serviceevent",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="serviceevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("start_time__isnull", True),
                    ("end_time__isnull", True),
                    ("end_time__gte", models.F("start_time")),
                    _connector="OR",
                ),
                name="attendance_service_event_end_time_after_start_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="memberattendance",
            constraint=models.UniqueConstraint(
                fields=("service_event", "member"),
                name="unique_member_attendance_per_service_event_member",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancesummary",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("men_count__gte", 0),
                    ("women_count__gte", 0),
                    ("children_count__gte", 0),
                    ("visitor_count__gte", 0),
                    ("total_count__gte", 0),
                ),
                name="attendance_summary_counts_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancesummary",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "total_count",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("men_count"), "+", models.F("women_count")
                            ),
                            "+",
                            models.F("children_count"),
                        ),
                    )
                ),
                name="attendance_summary_total_matches_components",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancesummary",
            constraint=models.CheckConstraint(
                condition=models.Q(("visitor_count__lte", models.F("total_count"))),
                name="attendance_summary_visitor_count_within_total",
            ),
        ),
    ]
