# Generated by Django 5.2.12 on 2026-04-03 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceevent',
            name='is_system_managed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='serviceevent',
            constraint=models.UniqueConstraint(condition=models.Q(('event_type', 'SUNDAY_SERVICE'), ('is_system_managed', True)), fields=('service_date',), name='attendance_unique_system_sunday_service_per_date'),
        ),
    ]
