# Generated by Django 5.2.12 on 2026-04-04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_serviceevent_is_system_managed_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="serviceevent",
            name="attendance_unique_system_sunday_service_per_date",
        ),
        migrations.RemoveField(
            model_name="serviceevent",
            name="is_system_managed",
        ),
    ]
