[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
django_find_project = false
pythonpath = backend
testpaths =
    backend/apps
    backend/tests
python_files =
    tests.py
    test_*.py
    *_tests.py
norecursedirs =
    .git
    .pytest_cache
    .venv
    backend/.venv
    docs
    frontend
    infra
