# Generated by Django 5.2.12 on 2026-03-27 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("target_type", models.CharField(db_index=True, max_length=64)),
                ("target_id", models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ("summary", models.CharField(max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"], name="common_audi_event_t_a6c254_idx"
                    ),
                    models.Index(
                        fields=["target_type", "target_id", "created_at"],
                        name="common_audi_target__659ee3_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"], name="common_audi_actor_i_a7ab54_idx"
                    ),
                ],
            },
        ),
    ]
