# Generated by Django 5.2.12 on 2026-04-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='external_reference',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
    ]
